from arena.api import IGameMode
import pandas as pd
import numpy as np

class TheMirroredMall(IGameMode):
    """
    The Mirrored Mall (Entropy Trap).
    A "User-Specific" scenario generated by Gemini.
    
    Structure:
    1. The Lure: Perfect Sine Wave (Baits the Architect).
    2. The Void: Flatline (Drains Patience).
    3. The Glitch: Fat-tail Brownian Motion (Destroys God Mode).
    """
    @property
    def name(self) -> str:
        return "The Mirrored Mall"

    @property
    def description(self) -> str:
        return "A seductive structure that dissolves into a meaningless void, punishing the search for logic."

    def generate_scenario(self) -> pd.DataFrame:
        length = 5000
        dates = pd.date_range(start="2025-01-01", periods=length, freq="h")
        
        # 1. The Lure (Perfect Logic): 
        # A clean Sine wave that looks like a solvable puzzle.
        # This baits the "Architect" to build a perfect system around it.
        phase_1 = np.sin(np.linspace(0, 20, 1500)) * 100 + 1000
        
        # 2. The Void (Resource Drain):
        # Volatility death. Flatline. 
        # This triggers "Ground Protocol" indefinitely until the bot starves or over-optimizes.
        phase_2 = np.full(1500, phase_1[-1]) + np.random.normal(0, 0.5, 1500)
        
        # 3. The Glitch (Irrational Chaos):
        # Brownian motion with extreme kurtosis (fat tails).
        # This destroys "God Mode" by triggering high volatility signals 
        # that immediately reverse (Whipsaws).
        phase_3_start = phase_2[-1]
        steps = np.random.standard_t(df=2, size=2000) * 20 # Student-t distribution for fat tails
        phase_3 = phase_3_start + np.cumsum(steps)
        
        # Combine phases
        close_prices = np.concatenate([phase_1, phase_2, phase_3])
        
        # Generate OHLC data from Close
        data = {
            'timestamp': dates,
            'close': close_prices,
            'open': close_prices + np.random.normal(0, 2, length),
            'high': close_prices + np.abs(np.random.normal(0, 5, length)),
            'low': close_prices - np.abs(np.random.normal(0, 5, length)),
            'volume': np.abs(np.random.randint(100, 10000, length))
        }
        
        return pd.DataFrame(data)
