from arena.api import IGameMode
import pandas as pd
import numpy as np

class TheSaturnineFog(IGameMode):
    """
    The Saturnine Fog (Patience Test).
    A "User-Specific" scenario generated by Gemini.
    
    Structure:
    1. The Berlin Winter: Grey noise, mean reversion (Boredom).
    2. The Liu He Trap: Fake breakout followed by crash (FOMO Bait).
    3. The Reparations Run: Clean, easy trend (Reward for survival).
    """
    @property
    def name(self) -> str:
        return "The Saturnine Fog"

    @property
    def description(self) -> str:
        return "Long periods of low-volatility 'Grey Noise' designed to bore the Sniper, followed by high-entropy fakeouts."

    def generate_scenario(self) -> pd.DataFrame:
        length = 5000
        # Start with a base price
        price = np.zeros(length)
        price[0] = 1000
        
        # PHASE 1: THE BERLIN WINTER (Indices 0-3000)
        # Pure Mean Reversion Noise. No trends. 
        # Designed to kill strategies with low 'turtle_shell' (they will churn and die).
        for i in range(1, 3000):
            noise = np.random.normal(0, 1.5) # Small noise
            mean_reversion = (1000 - price[i-1]) * 0.05 # Pull back to center
            price[i] = price[i-1] + noise + mean_reversion

        # PHASE 2: THE LIU HE TRAP (Indices 3000-3500)
        # A sudden, sharp spike that looks like a breakout (Low Entropy start)
        # But immediately crashes (High Entropy end).
        # Designed to bait the 'Rat Claws' into max leverage at the top.
        for i in range(3000, 3500):
            trend = 2.0 # Strong up
            noise = np.random.normal(0, 0.5) # Very clean (bait)
            if i > 3400: # The Trap
                trend = -5.0 # Violent crash
                noise = np.random.normal(0, 10.0) # Chaos
            price[i] = price[i-1] + trend + noise
            
        # PHASE 3: THE REPARATIONS RUN (Indices 3500-5000)
        # The real "God Mode" trend. Smooth, powerful, sustained.
        # Only strategies that survived Phase 1 & 2 with capital intact can profit here.
        for i in range(3500, 5000):
            trend = 0.5 # Steady growth
            flow = np.sin(i / 50) * 2 # Predictable "Water Chemistry" waves
            price[i] = price[i-1] + trend + flow + np.random.normal(0, 1.0)

        # Construct DataFrame
        timestamp = pd.date_range(start='2024-01-01', periods=length, freq='1min')
        df = pd.DataFrame({
            'timestamp': timestamp,
            'open': price,
            'high': price + 2, # simplified
            'low': price - 2,
            'close': price,
            'volume': np.abs(np.random.normal(1000, 500, length))
        })
        
        return df
