/**
 * PROPHECY View Module
 * PROPHECY Alert Center
 */

/**
 * Patch onclick handlers to use router navigation
 */
function patchOnClickHandlers(element) {
    // Patch viewChart buttons - handle both simple and complex calls
    element.querySelectorAll('button[onclick*="viewChart"]').forEach(btn => {
        const onclick = btn.getAttribute('onclick');
        if (!onclick) return;
        
        // Match viewChart('SYMBOL', {...}) pattern
        const complexMatch = onclick.match(/viewChart\(['"]([^'"]+)['"]\s*,\s*({[^}]*})\)/);
        const simpleMatch = onclick.match(/viewChart\(['"]([^'"]+)['"]\)/);
        
        if (complexMatch || simpleMatch) {
            const symbol = (complexMatch || simpleMatch)[1];
            let prophecyData = null;
            
            if (complexMatch) {
                try {
                    prophecyData = JSON.parse(complexMatch[2]);
                } catch (e) {
                    console.warn('[PROPHECY] Failed to parse prophecy data', e);
                }
            }
            
            btn.removeAttribute('onclick');
            btn.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                
                const params = { 
                    symbol: symbol, 
                    showPredictions: 'true',
                    showProphecy: 'true'
                };
                
                if (prophecyData) {
                    if (prophecyData.timestamp) {
                        params.highlightTime = prophecyData.timestamp;
                    }
                    if (prophecyData.price) {
                        params.highlightPrice = prophecyData.price.toString();
                    }
                }
                
                if (window.router && window.router.navigateTo) {
                    window.router.navigateTo('chartview', params);
                } else {
                    const queryString = new URLSearchParams(params).toString();
                    window.location.hash = `#chartview?${queryString}`;
                }
            });
        }
    });
}

async function init(container, params = {}) {
    console.log('[PROPHECY] Initializing...', params);
    
    try {
        const response = await fetch('./prophecy/index.html');
        const html = await response.text();
        
        const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
        if (styleMatch) {
            const styleEl = document.createElement('style');
            styleEl.textContent = styleMatch[1];
            document.head.appendChild(styleEl);
        }
        
        const bodyMatch = html.match(/<body>([\s\S]*?)<\/body>/);
        if (bodyMatch) {
            const tempDiv = document.createElement('div');
            tempDiv.innerHTML = bodyMatch[1];
            
            const navLinks = tempDiv.querySelectorAll('.nav a');
            navLinks.forEach(link => {
                const href = link.getAttribute('href');
                if (href) {
                    if (href.includes('localhost:1420')) link.setAttribute('href', '#dashboard');
                    else if (href.includes('localhost:1423')) link.setAttribute('href', '#chartview');
                    else if (href.includes('localhost:1427')) link.setAttribute('href', '#opportunities');
                    else if (href.includes('localhost:1429')) link.setAttribute('href', '#scanner');
                    else if (href.includes('localhost:1424')) link.setAttribute('href', '#analytics');
                    link.removeAttribute('target');
                }
            });
            
            // Patch onclick handlers before injecting
            patchOnClickHandlers(tempDiv);
            
            container.innerHTML = tempDiv.innerHTML;
            
            // Re-patch after injection (in case HTML was regenerated by scripts)
            setTimeout(() => patchOnClickHandlers(container), 100);
        }
        
        // Override viewChart function before scripts execute
        window.viewChart = function(symbol, prophecyData = null) {
            const params = { 
                symbol: symbol, 
                showPredictions: 'true',
                showProphecy: 'true'
            };
            
            if (prophecyData) {
                if (prophecyData.timestamp) {
                    params.highlightTime = prophecyData.timestamp;
                }
                if (prophecyData.price) {
                    params.highlightPrice = prophecyData.price.toString();
                }
            }
            
            if (window.router && window.router.navigateTo) {
                window.router.navigateTo('chartview', params);
            } else {
                const queryString = new URLSearchParams(params).toString();
                window.location.hash = `#chartview?${queryString}`;
            }
        };
        
        const scriptMatches = html.matchAll(/<script>([\s\S]*?)<\/script>/g);
        for (const match of scriptMatches) {
            const scriptContent = match[1];
            if (scriptContent.includes('export') || scriptContent.includes('import ')) continue;
            
            // Remove the original viewChart function definition to use our override
            const patchedScript = scriptContent.replace(
                /function\s+viewChart\s*\([^)]*\)\s*\{[^}]*\}/gs,
                '// viewChart function overridden by router'
            );
            
            const scriptFunc = new Function(patchedScript);
            scriptFunc();
        }
        
        // Re-patch after scripts execute and set up MutationObserver
        setTimeout(() => {
            patchOnClickHandlers(container);
            
            const observer = new MutationObserver((mutations) => {
                mutations.forEach((mutation) => {
                    mutation.addedNodes.forEach((node) => {
                        if (node.nodeType === 1) {
                            if (node.matches && node.matches('button[onclick*="viewChart"]')) {
                                patchOnClickHandlers(node.parentElement || container);
                            } else if (node.querySelectorAll) {
                                const buttons = node.querySelectorAll('button[onclick*="viewChart"]');
                                if (buttons.length > 0) {
                                    patchOnClickHandlers(node);
                                }
                            }
                        }
                    });
                });
            });
            
            observer.observe(container, { childList: true, subtree: true });
            container._prophecyObserver = observer;
        }, 200);
        
        console.log('[PROPHECY] Initialized');
    } catch (error) {
        console.error('[PROPHECY] Failed to load:', error);
        container.innerHTML = `<div style="padding: 40px; text-align: center; color: #f87171;"><h2>Error Loading PROPHECY</h2><p>${error.message}</p></div>`;
    }
}

async function destroy() {
    console.log('[PROPHECY] Destroying...');
    if (window.prophecyUpdateInterval) {
        clearInterval(window.prophecyUpdateInterval);
        window.prophecyUpdateInterval = null;
    }
    
    // Clean up MutationObserver if it exists
    const container = document.getElementById('view-container');
    if (container && container._prophecyObserver) {
        container._prophecyObserver.disconnect();
        container._prophecyObserver = null;
    }
    
    // Clean up global navigation function
    if (window.viewChart && window.viewChart.toString().includes('prophecy')) {
        delete window.viewChart;
    }
    
    console.log('[PROPHECY] Destroyed');
}

export default { init, destroy };
