/**
 * Scanner View Module
 * Multi-symbol market scanner
 */

/**
 * Patch onclick handlers to use router navigation
 */
function patchOnClickHandlers(element) {
    // Patch viewChart buttons
    element.querySelectorAll('button[onclick*="viewChart"]').forEach(btn => {
        const onclick = btn.getAttribute('onclick');
        if (!onclick) return;
        
        const symbolMatch = onclick.match(/viewChart\(['"]([^'"]+)['"]\)/);
        if (symbolMatch) {
            const symbol = symbolMatch[1];
            btn.removeAttribute('onclick');
            btn.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                if (window.router && window.router.navigateTo) {
                    window.router.navigateTo('chartview', { symbol: symbol });
                } else {
                    window.location.hash = `#chartview?symbol=${encodeURIComponent(symbol)}`;
                }
            });
        }
    });
    
    // Patch viewOpportunities buttons
    element.querySelectorAll('button[onclick*="viewOpportunities"]').forEach(btn => {
        const onclick = btn.getAttribute('onclick');
        if (!onclick) return;
        
        const symbolMatch = onclick.match(/viewOpportunities\(['"]([^'"]+)['"]\)/);
        if (symbolMatch) {
            const symbol = symbolMatch[1];
            btn.removeAttribute('onclick');
            btn.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                if (window.router && window.router.navigateTo) {
                    window.router.navigateTo('opportunities', { symbol: symbol });
                } else {
                    window.location.hash = `#opportunities?symbol=${encodeURIComponent(symbol)}`;
                }
            });
        }
    });
    
    // Patch viewProphecy buttons
    element.querySelectorAll('button[onclick*="viewProphecy"]').forEach(btn => {
        const onclick = btn.getAttribute('onclick');
        if (!onclick) return;
        
        const symbolMatch = onclick.match(/viewProphecy\(['"]([^'"]+)['"]\)/);
        if (symbolMatch) {
            const symbol = symbolMatch[1];
            btn.removeAttribute('onclick');
            btn.addEventListener('click', (e) => {
                e.preventDefault();
                e.stopPropagation();
                if (window.router && window.router.navigateTo) {
                    window.router.navigateTo('prophecy', { symbol: symbol });
                } else {
                    window.location.hash = `#prophecy?symbol=${encodeURIComponent(symbol)}`;
                }
            });
        }
    });
}

async function init(container, params = {}) {
    console.log('[Scanner] Initializing...', params);
    
    try {
        const response = await fetch('./scanner/index.html');
        const html = await response.text();
        
        const styleMatch = html.match(/<style>([\s\S]*?)<\/style>/);
        if (styleMatch) {
            const styleEl = document.createElement('style');
            styleEl.textContent = styleMatch[1];
            document.head.appendChild(styleEl);
        }
        
        const bodyMatch = html.match(/<body>([\s\S]*?)<\/body>/);
        if (bodyMatch) {
            const tempDiv = document.createElement('div');
            tempDiv.innerHTML = bodyMatch[1];
            
            const navLinks = tempDiv.querySelectorAll('.nav a');
            navLinks.forEach(link => {
                const href = link.getAttribute('href');
                if (href) {
                    if (href.includes('localhost:1420')) link.setAttribute('href', '#dashboard');
                    else if (href.includes('localhost:1423')) link.setAttribute('href', '#chartview');
                    else if (href.includes('localhost:1427')) link.setAttribute('href', '#opportunities');
                    else if (href.includes('localhost:1428')) link.setAttribute('href', '#prophecy');
                    else if (href.includes('localhost:1424')) link.setAttribute('href', '#analytics');
                    link.removeAttribute('target');
                }
            });
            
            // Patch onclick handlers for navigation buttons
            patchOnClickHandlers(tempDiv);
            
            container.innerHTML = tempDiv.innerHTML;
            
            // Re-patch after injection (in case HTML was regenerated by scripts)
            setTimeout(() => patchOnClickHandlers(container), 100);
        }
        
        // Override navigation functions before scripts execute
        window.viewChart = function(symbol) {
            if (window.router && window.router.navigateTo) {
                window.router.navigateTo('chartview', { symbol: symbol });
            } else {
                window.location.hash = `#chartview?symbol=${encodeURIComponent(symbol)}`;
            }
        };
        
        window.viewOpportunities = function(symbol) {
            if (window.router && window.router.navigateTo) {
                window.router.navigateTo('opportunities', { symbol: symbol });
            } else {
                window.location.hash = `#opportunities?symbol=${encodeURIComponent(symbol)}`;
            }
        };
        
        window.viewProphecy = function(symbol) {
            if (window.router && window.router.navigateTo) {
                window.router.navigateTo('prophecy', { symbol: symbol });
            } else {
                window.location.hash = `#prophecy?symbol=${encodeURIComponent(symbol)}`;
            }
        };
        
        const scriptMatches = html.matchAll(/<script>([\s\S]*?)<\/script>/g);
        for (const match of scriptMatches) {
            const scriptContent = match[1];
            if (scriptContent.includes('export') || scriptContent.includes('import ')) continue;
            
            // Note: We define global functions above, so script's local function definitions
            // will be shadowed. The global functions will be called by onclick handlers.
            // We don't need to remove the function definitions from scripts since they're
            // in function scope and won't override our global ones.
            
            const scriptFunc = new Function(scriptContent);
            scriptFunc();
        }
        
        // Re-patch after scripts execute (they may regenerate HTML)
        setTimeout(() => {
            patchOnClickHandlers(container);
            // Also set up MutationObserver to patch dynamically added buttons
            const observer = new MutationObserver((mutations) => {
                mutations.forEach((mutation) => {
                    mutation.addedNodes.forEach((node) => {
                        if (node.nodeType === 1) { // Element node
                            if (node.matches && (node.matches('button[onclick*="viewChart"]') || 
                                node.matches('button[onclick*="viewOpportunities"]') || 
                                node.matches('button[onclick*="viewProphecy"]'))) {
                                patchOnClickHandlers(node.parentElement || container);
                            } else if (node.querySelectorAll) {
                                const buttons = node.querySelectorAll('button[onclick*="viewChart"], button[onclick*="viewOpportunities"], button[onclick*="viewProphecy"]');
                                if (buttons.length > 0) {
                                    patchOnClickHandlers(node);
                                }
                            }
                        }
                    });
                });
            });
            
            observer.observe(container, { childList: true, subtree: true });
            
            // Store observer for cleanup
            container._scannerObserver = observer;
        }, 200);
        
        console.log('[Scanner] Initialized');
    } catch (error) {
        console.error('[Scanner] Failed to load:', error);
        container.innerHTML = `<div style="padding: 40px; text-align: center; color: #f87171;"><h2>Error Loading Scanner</h2><p>${error.message}</p></div>`;
    }
}

async function destroy() {
    console.log('[Scanner] Destroying...');
    if (window.scannerUpdateInterval) {
        clearInterval(window.scannerUpdateInterval);
        window.scannerUpdateInterval = null;
    }
    
    // Clean up MutationObserver if it exists
    const container = document.getElementById('view-container');
    if (container && container._scannerObserver) {
        container._scannerObserver.disconnect();
        container._scannerObserver = null;
    }
    
    // Clean up global navigation functions
    if (window.viewChart) delete window.viewChart;
    if (window.viewOpportunities) delete window.viewOpportunities;
    if (window.viewProphecy) delete window.viewProphecy;
    
    console.log('[Scanner] Destroyed');
}

export default { init, destroy };
