from arena.api import IStrategy
import pandas as pd
import numpy as np

class TheAlchemicArchitect(IStrategy):
    """
    The Alchemic Architect (Nika).
    A "User-DNA" strategy generated by Gemini.
    
    Concept:
    - Ground Protocol: Refuses to trade 'noise'. Builds structure.
    - God Mode: Aggressive flow state when volatility triggers 'The Zone'.
    """
    @property
    def name(self) -> str:
        return "The Alchemic Architect"

    @property
    def class_type(self) -> str:
        return "HYBRID" # Structure + Chaos

    def __init__(self):
        super().__init__()
        # DNA: Your Personality Encoded
        self.skills = {
            # Ground Protocol: How long to observe before acting (Patience/Input)
            "maintenance_period": 20, 
            
            # God Mode: How aggressively to scale in when "The Zone" is hit
            "alchemic_intensity": 2.5, 
            
            # Structure: The rigid logic protecting the core (Stop Loss tightness)
            "structural_integrity": 0.05,
            
            # The Trigger: Threshold of volatility needed to wake the Alchemist
            "activation_threshold": 1.5 
        }
        
        # Internal State
        self.state = "GROUND_PROTOCOL" # vs "GOD_MODE"

    def on_tick(self, packet: dict) -> float:
        return 0.0

    def next_candle(self, df: pd.DataFrame) -> float:
        # 1. Input Phase: Gather Data
        if len(df) < self.skills['maintenance_period']:
            return 0.0
            
        period = int(self.skills['maintenance_period'])
        recent_data = df.iloc[-period:]
        
        # 2. Analyze Structure (Volatility & Trend)
        # Using Standard Deviation as a proxy for "Heat/Energy"
        volatility = recent_data['close'].std()
        
        # Calculate Trend (Simple Moving Average slope)
        sma = recent_data['close'].mean()
        current_price = df['close'].iloc[-1]
        
        # Normalize volatility against price to get a ratio
        if current_price == 0: return 0.0
        norm_vol = (volatility / current_price) * 100
        
        # 3. The Nika Algorithm: Switching States
        
        # State: GROUND PROTOCOL (10:00 - 13:00)
        # If market is flat/boring, we wait. We do not force action.
        if norm_vol < self.skills['activation_threshold']:
            self.state = "GROUND_PROTOCOL"
            return 0.0 # Cash is a position.
            
        # State: GOD MODE (22:00 - 02:00)
        # High energy detected. We abandon caution for pure flow.
        self.state = "GOD_MODE"
        
        # Directional Logic:
        # If we are above structure (SMA), we push HARD (Long).
        # If we are below structure, we short HARD.
        if current_price > sma:
            # We scale size based on Alchemic Intensity (Conviction)
            # Clip simply to avoid absurd values if skills mutate wild.
            return min(1.0, 1.0 * self.skills['alchemic_intensity'])
        else:
            return max(-1.0, -1.0 * self.skills['alchemic_intensity'])

    def evolve(self, mutation_rate: float = 0.1) -> 'TheAlchemicArchitect':
        child = TheAlchemicArchitect()
        
        # Evolution: Sometimes the Architect becomes more rigid, 
        # sometimes the Alchemist becomes more reckless.
        for key, value in self.skills.items():
            mutation = np.random.normal(0, mutation_rate * value)
            child.skills[key] = abs(value + mutation) # Skills can't be negative
            
        return child
