from arena.api import IStrategy
import pandas as pd
import numpy as np

class TheJadeProtocol(IStrategy):
    """
    The Jade Protocol (Rat & Turtle).
    A "User-DNA" strategy generated by Gemini.
    
    Concept:
    - The Turtle (Entropy Filter): Sleeps during chaotic/boring markets.
    - The Rat (Alchemical Sniper): Strikes with leverage when flow is clean.
    """
    @property
    def name(self) -> str:
        return "The Jade Protocol"

    @property
    def class_type(self) -> str:
        return "SNIPER"

    def __init__(self):
        super().__init__()
        # The DNA of the Strategy
        self.skills = {
            "turtle_shell": 0.8,    # Entropy Threshold (Higher = More picky/Patient)
            "rat_claws": 2.5,       # Aggression Multiplier (Leverage when striking)
            "flow_memory": 14       # Lookback period (Water Chemistry)
        }

    def calculate_entropy(self, df: pd.DataFrame) -> float:
        """
        Calculates the 'Chaos' of the market.
        Uses a simplified Hurst-like proxy: Volatility / Range.
        High Value = Choppy (Don't Trade). Low Value = Clean Flow (God Mode).
        """
        window = int(self.skills['flow_memory'])
        if len(df) < window:
            return 1.0 # Default to high entropy (safety)
            
        recent_data = df.iloc[-window:]
        
        # Calculate 'Roughness' vs 'Direction'
        # If price moves 100 points but traveled 500 points to get there -> High Entropy
        total_path = np.sum(np.abs(recent_data['close'].diff()))
        net_move = np.abs(recent_data['close'].iloc[-1] - recent_data['close'].iloc[0])
        
        if net_move == 0: return 1.0
        
        # Efficiency Ratio (Kaufman). 1.0 is a straight line. 0.0 is pure noise.
        # We invert it so 1.0 is Chaos (Entropy).
        efficiency = net_move / total_path if total_path > 0 else 0
        entropy = 1.0 - efficiency 
        return entropy

    def on_tick(self, packet: dict) -> float:
        return 0.0

    def next_candle(self, df: pd.DataFrame) -> float:
        # 1. THE TURTLE CHECK (Structure)
        current_entropy = self.calculate_entropy(df)
        
        # If the market is too chaotic (Entropy > (1 - Threshold)), SLEEP.
        # This prevents the '27-day burnout'.
        if current_entropy > (1.0 - self.skills['turtle_shell']):
            return 0.0 # Airplane Mode
            
        # 2. THE RAT STRIKE (Alchemist)
        # If we passed the Turtle Check, we enter "God Mode".
        lookback = int(self.skills['flow_memory'])
        momentum = df['close'].iloc[-1] - df['close'].iloc[-lookback]
        
        # Normalize momentum signal (-1 to 1)
        if momentum == 0: return 0.0
        signal = np.sign(momentum)
        
        # Apply "Rat Claws" (Aggression)
        # We don't just buy; we scale based on how CLEAN the move is.
        confidence = (1.0 - current_entropy) # The cleaner the move, the harder we hit.
        final_output = signal * confidence * self.skills['rat_claws']
        
        # Clamp between -1.0 and 1.0
        return max(-1.0, min(1.0, final_output))

    def evolve(self, mutation_rate: float = 0.1) -> 'TheJadeProtocol':
        child = TheJadeProtocol()
        # Evolution Logic: 
        # Sometimes the Rat gets greedier (higher claws), 
        # Sometimes the Turtle gets harder (higher shell).
        child.skills['turtle_shell'] = np.clip(self.skills['turtle_shell'] + np.random.normal(0, mutation_rate), 0.1, 0.99)
        child.skills['rat_claws'] = np.clip(self.skills['rat_claws'] + np.random.normal(0, mutation_rate), 1.0, 5.0)
        child.skills['flow_memory'] = max(5, int(self.skills['flow_memory'] + np.random.normal(0, 2)))
        return child
