<template>
  <div class="self-hub-view">
    <div class="hub-container">
      <div class="tree-root">
        
        <!-- Identity Node -->
        <div class="tree-node">
          <div class="node-content">
            <span class="branch-line root"></span>
            <span class="keyword">def</span> <span class="entity">observer</span>():
          </div>
          
          <!-- Anchors Block -->
          <div class="tree-children">
            <div class="tree-node">
              <div class="node-content">
                <span class="branch-line"></span>
                <span class="keyword">class</span> <span class="entity">RealityAnchors</span>:
              </div>
              
              <div class="tree-children">
                <!-- Anchor Items -->
                <div 
                  v-for="(anchor, idx) in anchors" 
                  :key="idx" 
                  class="tree-node anchor-item"
                >
                  <div class="node-content anchor-row">
                    <span class="branch-line leaf"></span>
                    <span class="bullet">yield</span>
                    <input 
                      v-model="anchor.text" 
                      @blur="saveAnchors"
                      @keydown.enter="addAnchor(idx)"
                      @keydown.backspace="handleBackspace(idx, $event)"
                      class="tree-input"
                      placeholder='e.g. "Value is generated by resonance"'
                      ref="anchorInputs"
                    />
                    <button class="remove-btn" @click="removeAnchor(idx)" title="Remove Anchor">×</button>
                  </div>
                </div>
                
                <!-- Add new anchor -->
                <div class="tree-node anchor-item" v-if="anchors.length === 0">
                  <div class="node-content anchor-row">
                    <span class="branch-line leaf"></span>
                    <span class="bullet pulse">yield</span>
                    <input 
                      @keydown.enter="addAnchor(-1)"
                      class="tree-input empty"
                      placeholder="Evolve your first fundamental truth..."
                    />
                  </div>
                </div>
              </div>
            </div>
            
            <!-- Vibe / State Block -->
            <div class="tree-node mt-4">
              <div class="node-content">
                <span class="branch-line"></span>
                <span class="keyword">def</span> <span class="entity">current_vibe</span>():
              </div>
              
              <div class="tree-children">
                <div class="tree-node">
                  <div class="node-content">
                    <span class="branch-line leaf"></span>
                    <span class="keyword">return</span>
                    <input 
                      v-model="currentVibe" 
                      @blur="saveAnchors"
                      class="tree-input string"
                      placeholder="'listening to the swarm...'"
                    />
                  </div>
                </div>
              </div>
            </div>

            <!-- Aesthetic Block -->
            <div class="tree-node mt-4">
              <div class="node-content">
                <span class="branch-line"></span>
                <span class="keyword">class</span> <span class="entity">Aesthetic</span>:
              </div>
              <div class="tree-children">
                 <div class="tree-node anchor-item">
                    <div class="node-content anchor-row">
                      <span class="branch-line leaf"></span>
                      <span class="bullet">import</span>
                      <input 
                        v-model="customThemeUrl"
                        @blur="applyCustomTheme"
                        @keydown.enter="applyCustomTheme"
                        class="tree-input string"
                        placeholder="'https://example.com/theme.css'"
                      />
                    </div>
                 </div>
              </div>
            </div>

            <!-- Manifold Connection -->
            <div class="tree-node mt-4">
              <div class="node-content">
                <span class="branch-line"></span>
                <span class="comment"># Initialize connection to LGNN</span>
              </div>
              <div class="node-content mt-1">
                <span class="branch-line"></span>
                <button @click="syncToMatrix" class="sync-btn" :class="{ active: isSyncing }">
                  <span v-if="!isSyncing">manifold.connect()</span>
                  <span v-else>syncing...</span>
                </button>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue'
import { API_BASE } from '../shared/api.js'

interface Anchor {
  text: string
}

const anchors = ref<Anchor[]>([
  { text: '"The market is a liquid ecology of beliefs"' },
  { text: '"Value is generated by resonating with the swarm"' }
])

const currentVibe = ref('"Open, altruistic, seeking resonance"')
const customThemeUrl = ref("''")
const isSyncing = ref(false)
const anchorInputs = ref<HTMLInputElement[]>([])

onMounted(() => {
  const saved = localStorage.getItem('lgnn-hub-anchors')
  if (saved) {
    try {
      const parsed = JSON.parse(saved)
      anchors.value = parsed.anchors || []
      currentVibe.value = parsed.vibe || ''
      customThemeUrl.value = parsed.theme || "''"
      applyCustomTheme()
    } catch (e) {}
  }
})

function applyCustomTheme() {
  saveAnchors()
  
  let url = customThemeUrl.value.replace(/['"]/g, '').trim()
  let link = document.getElementById('custom-theme-link') as HTMLLinkElement
  
  if (!url) {
    if (link) link.remove()
    return
  }

  if (!link) {
    link = document.createElement('link')
    link.id = 'custom-theme-link'
    link.rel = 'stylesheet'
    document.head.appendChild(link)
  }
  
  if (link.href !== url) {
    link.href = url
  }
}

function saveAnchors() {
  // Clean up empty anchors
  anchors.value = anchors.value.filter(a => a.text.trim() !== '')
  if (anchors.value.length === 0) {
    anchors.value.push({ text: '' })
  }
  
  localStorage.setItem('lgnn-hub-anchors', JSON.stringify({
    anchors: anchors.value,
    vibe: currentVibe.value,
    theme: customThemeUrl.value
  }))
}

function addAnchor(index: number) {
  anchors.value.splice(index + 1, 0, { text: '' })
  nextTick(() => {
    if (anchorInputs.value && anchorInputs.value[index + 1]) {
      anchorInputs.value[index + 1].focus()
    }
  })
}

function handleBackspace(index: number, event: KeyboardEvent) {
  if (anchors.value[index].text === '' && anchors.value.length > 1) {
    event.preventDefault()
    removeAnchor(index)
  }
}

function removeAnchor(index: number) {
  anchors.value.splice(index, 1)
  saveAnchors()
  nextTick(() => {
    const prev = index > 0 ? index - 1 : 0
    if (anchorInputs.value && anchorInputs.value[prev]) {
      anchorInputs.value[prev].focus()
    }
  })
}

async function syncToMatrix() {
  isSyncing.value = true
  
  try {
    // In a real scenario, we'd POST these to the backend to set `is_grounded = True`
    // For now, we simulate the systemic calibration
    const allText = anchors.value.map(a => a.text).join(' ') + ' ' + currentVibe.value
    await fetch(`${API_BASE}/lgnn/evolve-text`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: `[HUB CALIBRATION] ${allText}` })
    })
    saveAnchors()
  } catch (e) {
    console.error(e)
  } finally {
    setTimeout(() => {
      isSyncing.value = false
    }, 800)
  }
}
</script>

<style scoped>
.self-hub-view {
  width: 100%;
  height: 100%;
  background: #FFF;
  color: #1A1A1A;
  display: flex;
  justify-content: flex-start;
  align-items: flex-start;
  font-family: 'Space Mono', monospace;
  overflow: auto;
  padding: 10px;
  box-sizing: border-box;
}

.hub-container {
  width: 100%;
  max-width: 100%;
  padding: 0;
  background: #FFF;
  border-radius: 0;
  box-shadow: none;
  border: none;
}

.tree-root {
  display: flex;
  flex-direction: column;
}

.tree-node {
  position: relative;
  display: flex;
  flex-direction: column;
}

.node-content {
  display: flex;
  align-items: center;
  padding: 6px 0;
  font-size: 14px;
  line-height: 1.5;
  font-weight: 900;
}

.tree-children {
  margin-left: 20px;
  border-left: 2px solid #1A1A1A;
  padding-left: 10px;
  display: flex;
  flex-direction: column;
}

.branch-line {
  position: relative;
  width: 16px;
  height: 2px;
  background: #1A1A1A;
  margin-right: 8px;
  display: inline-block;
}

.branch-line.root {
  background: transparent;
}

.keyword {
  color: #E03C31; /* Red */
  margin-right: 8px;
  font-weight: 900;
  text-transform: uppercase;
}

.entity {
  color: #1A1A1A;
  font-weight: 900;
}

.comment {
  color: #666;
  font-style: italic;
}

.bullet {
  color: #F2C12E; /* Yellow */
  margin-right: 8px;
  text-transform: uppercase;
  font-weight: 900;
}

.tree-input {
  background: #FFF;
  border: 2px solid #1A1A1A;
  color: #1A1A1A;
  font-family: inherit;
  font-size: 14px;
  font-weight: 900;
  outline: none;
  flex: 1;
  padding: 4px 8px;
  border-radius: 0;
  box-shadow: 2px 2px 0px #1A1A1A;
}

.tree-input::placeholder {
  color: #999;
  font-style: italic;
}

.tree-input:focus {
  background: #F2C12E;
  border-color: #1A1A1A;
}

.tree-input.empty {
  color: #666;
}

.tree-input.string {
  color: #1A1A1A;
}

.anchor-row {
  position: relative;
}

.remove-btn {
  background: #E03C31;
  border: 2px solid #1A1A1A;
  color: #FFF;
  font-size: 14px;
  font-weight: 900;
  cursor: pointer;
  padding: 2px 6px;
  margin-left: 5px;
  box-shadow: 2px 2px 0px #1A1A1A;
}

.remove-btn:active {
  box-shadow: 0px 0px 0px #1A1A1A;
  transform: translate(2px, 2px);
}

.mt-4 { margin-top: 16px; }
.mt-1 { margin-top: 4px; }

.sync-btn {
  background: #FFF;
  border: 2px solid #1A1A1A;
  color: #1A1A1A;
  font-family: inherit;
  font-weight: 900;
  font-size: 12px;
  padding: 4px 12px;
  border-radius: 0;
  cursor: pointer;
  box-shadow: 2px 2px 0px #1A1A1A;
  text-transform: uppercase;
}

.sync-btn:active {
  box-shadow: 0px 0px 0px #1A1A1A;
  transform: translate(2px, 2px);
}

.sync-btn.active {
  background: #F2C12E;
}
</style>
