# Database refactor: keep raw ticks but add storage for analytical artifacts
# Short summary of changes:
# - Centralized connection setup with sensible PRAGMAs for concurrency (WAL, synchronous=NORMAL).
# - Added tables: analyses, signals, trades, positions, performance_metrics.
# - Provided helper methods to insert/query those artifacts.
# - Use JSON serialization for payload/metadata and sqlite3.Row row_factory for clarity.
# Suggested quick checks after applying:
# - Run `python -c "from services.database import Database; Database()._init_db(); print('ok')"`
# - Inspect the DB with `sqlite3 market_data.db ".tables"` (or open with your DB viewer).
import sqlite3
import logging
import os
import json
from typing import List, Tuple, Optional, Any
from datetime import datetime
from functools import lru_cache
from collections import OrderedDict
import threading
import time

logger = logging.getLogger("AuraticDB")
SCHEMA_VERSION = 1


class Database:
    """
    Database helper for market ticks and analytical artifacts.

    Responsibilities:
    - Persist raw market ticks and analytical artifacts (analyses, signals, trades, positions, metrics).
    - Provide safe, parametrized helper methods for common operations.
    - Use WAL mode and sensible pragmas to improve concurrency and durability.
    """

    def __init__(self, db_path: str = "market_data.db"):
        self.db_path = db_path
        # Ensure directory exists if a nested path is provided
        db_dir = os.path.dirname(os.path.abspath(db_path))
        if db_dir and not os.path.exists(db_dir):
            try:
                os.makedirs(db_dir, exist_ok=True)
            except Exception:
                # In case of permission issues, continue and let sqlite raise later
                pass

        self._init_db()

        # in-memory caches to avoid recomputing heavy analyses (bounded to prevent memory bloat)
        self._analysis_cache = OrderedDict()  # key: (symbol, analysis_type) -> (cached_at, ts, payload)
        self._analysis_cache_max = 1000
        self._signals_cache = {}   # key: symbol -> {'ts': float, 'data': list}
        self._cache_ttl = 30.0     # seconds
        self._cache_lock = threading.Lock()

        # Run migrations if DB schema is behind.
        try:
            self._migrate()
        except Exception:
            logger.exception("Migration step failed during initialization")

    def _connect(self) -> sqlite3.Connection:
        """Create a connection with sensible defaults for concurrent reads/writes."""
        conn = sqlite3.connect(self.db_path, timeout=30.0, detect_types=sqlite3.PARSE_DECLTYPES)
        conn.row_factory = sqlite3.Row
        try:
            # Improve concurrency & durability for multi-threaded producers/consumers
            conn.execute("PRAGMA journal_mode=WAL;")
            conn.execute("PRAGMA synchronous=NORMAL;")
            conn.execute("PRAGMA foreign_keys=ON;")
        except Exception:
            # Some SQLite builds may not support WAL or PRAGMAs; ignore failures but log.
            logger.debug("Could not set PRAGMAs on connection.")
        return conn

    def _init_db(self):
        """Create base tables and indices if they don't already exist."""
        try:
            with self._connect() as conn:
                cursor = conn.cursor()
                # Raw market ticks (kept compatible with previous schema)
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS market_ticks (
                        symbol TEXT NOT NULL,
                        timestamp REAL NOT NULL,
                        price REAL,
                        volume REAL,
                        is_buyer_maker INTEGER,
                        PRIMARY KEY (symbol, timestamp)
                    )
                    """
                )
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_sym_time ON market_ticks(symbol, timestamp)")

                # Analytical outputs: cache physics/analysis results
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS analyses (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        symbol TEXT,
                        ts REAL NOT NULL,
                        analysis_type TEXT NOT NULL,
                        payload TEXT NOT NULL, -- JSON serialized
                        created_ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_analyses_sym_ts ON analyses(symbol, ts)")

                # Signals generated by strategy components
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS signals (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        symbol TEXT,
                        ts REAL NOT NULL,
                        signal TEXT NOT NULL, -- e.g. BUY/SELL/HOLD
                        params TEXT, -- JSON serialized params/metadata
                        created_ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_signals_sym_ts ON signals(symbol, ts)")

                # Executed trades / simulated trades
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS trades (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        user_id INTEGER DEFAULT 0,
                        symbol TEXT,
                        ts REAL NOT NULL,
                        action TEXT NOT NULL, -- BUY/SELL
                        price REAL,
                        quantity REAL,
                        metadata TEXT, -- JSON
                        created_ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_trades_user_sym_ts ON trades(user_id, symbol, ts)")

                # Signal->Trade mapping table (many-to-many/lookup)
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS signal_trade_map (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        signal_id INTEGER,
                        trade_id INTEGER,
                        ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )

                # Persistent positions (one row per user + symbol)
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS positions (
                        user_id INTEGER DEFAULT 0,
                        symbol TEXT,
                        quantity REAL NOT NULL,
                        avg_price REAL,
                        metadata TEXT,
                        updated_ts REAL DEFAULT (strftime('%s','now')),
                        PRIMARY KEY (user_id, symbol)
                    )
                    """
                )

                # Performance metrics (time-series of metric values)
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS performance_metrics (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        ts REAL NOT NULL,
                        metric_name TEXT NOT NULL,
                        value REAL,
                        tags TEXT, -- JSON metadata or tags
                        created_ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_metrics_name_ts ON performance_metrics(metric_name, ts)")


                # Ensure schema_version table exists and seed it if empty.
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS schema_version (
                        version INTEGER PRIMARY KEY,
                        applied_ts REAL DEFAULT (strftime('%s','now'))
                    )
                    """
                )
                cur = cursor.execute("SELECT COUNT(*) FROM schema_version")
                row = cur.fetchone()
                cnt = row[0] if row else 0
                if cnt == 0:
                    cursor.execute("INSERT INTO schema_version (version) VALUES (?)", (SCHEMA_VERSION,))
                conn.commit()
                logger.info(f"Database initialized at {self.db_path} (schema v={SCHEMA_VERSION})")
        except Exception as e:
            logger.exception(f"Failed to initialize database: {e}")

    def _get_schema_version(self) -> int:
        """Return current schema version stored in DB (0 if missing)."""
        try:
            with self._connect() as conn:
                cur = conn.execute("SELECT version FROM schema_version ORDER BY version DESC LIMIT 1")
                r = cur.fetchone()
                if not r:
                    return 0
                # sqlite3.Row supports dict-style access; fallback to index
                return int(r["version"]) if "version" in r.keys() else int(r[0])
        except sqlite3.OperationalError as e:
            # If table doesn't exist, we are at version 0
            if "no such table" in str(e).lower():
                return 0
            logger.exception("Operational error reading schema version")
            return 0
        except Exception:
            logger.exception("Error reading schema version")
            return 0

    def _set_schema_version(self, version: int):
        """Append a new applied schema version record."""
        try:
            with self._connect() as conn:
                conn.execute("INSERT INTO schema_version (version) VALUES (?)", (version,))
                conn.commit()
        except Exception:
            logger.exception("Error setting schema version")

    def _migrate(self):
        """
        Run any migrations required to bring DB to SCHEMA_VERSION.
        Add migration steps here as the schema evolves.
        """
        current = self._get_schema_version()
        if current >= SCHEMA_VERSION:
            return

        logger.info(f"Upgrading DB schema from {current} to {SCHEMA_VERSION}")
        # Example migration framework; append steps below conditioned on current version.
        try:
            # With SQLite, wrap multi-step migrations in a transaction.
            with self._connect() as conn:
                cur = conn.cursor()
                # <example> if current == 1 and SCHEMA_VERSION >= 2: ... </example>
                # No migrations defined yet; future migrations should be implemented here.
                conn.commit()
            # mark schema as updated
            self._set_schema_version(SCHEMA_VERSION)
            logger.info(f"Database schema upgraded to {SCHEMA_VERSION}")
        except Exception:
            logger.exception("Error applying migrations")
            raise

    # ---------- Market ticks (unchanged functionality, safer connections) ----------
    def insert_tick(self, symbol: str, timestamp: float, price: float, volume: float, is_buyer_maker: bool):
        """Insert a single tick. Uses INSERT OR REPLACE to handle overlaps."""
        try:
            with self._connect() as conn:
                conn.execute(
                    "INSERT OR REPLACE INTO market_ticks (symbol, timestamp, price, volume, is_buyer_maker) VALUES (?, ?, ?, ?, ?)",
                    (symbol, timestamp, price, volume, 1 if is_buyer_maker else 0),
                )
                conn.commit()
        except Exception:
            logger.exception("Error inserting tick")

    def insert_batch(self, ticks: List[Tuple]):
        """
        Insert a batch of ticks.
        ticks format: [(symbol, timestamp, price, volume, is_buyer_maker), ...]
        This method includes a short retry loop to handle transient SQLITE_LOCKED errors.
        """
        if not ticks:
            return

        attempts = 3
        delay = 0.05
        formatted_ticks = [(t[0], t[1], t[2], t[3], 1 if t[4] else 0) for t in ticks]
        for attempt in range(attempts):
            try:
                with self._connect() as conn:
                    conn.executemany(
                        "INSERT OR REPLACE INTO market_ticks (symbol, timestamp, price, volume, is_buyer_maker) VALUES (?, ?, ?, ?, ?)",
                        formatted_ticks,
                    )
                    conn.commit()
                return
            except sqlite3.OperationalError as e:
                # Retry on database locked
                if "locked" in str(e).lower() and attempt + 1 < attempts:
                    time.sleep(delay * (2 ** attempt))
                    continue
                logger.exception("SQLite operational error inserting batch")
                return
            except Exception:
                logger.exception("Error inserting batch")
                return

    def get_latest_timestamp(self, symbol: str) -> float:
        """Get the timestamp of the most recent tick for a symbol."""
        try:
            with self._connect() as conn:
                cur = conn.execute("SELECT MAX(timestamp) as mx FROM market_ticks WHERE symbol = ?", (symbol,))
                row = cur.fetchone()
                return float(row["mx"]) if row and row["mx"] is not None else 0.0
        except Exception:
            logger.exception("Error getting latest timestamp")
            return 0.0

    def get_history(self, symbol: str, limit: int = 20000) -> List[Tuple]:
        """Get the most recent N ticks for a symbol, ordered by timestamp ASC."""
        try:
            with self._connect() as conn:
                # Use parametrized query for limit by casting to int here (safe)
                limit = int(limit)
                cur = conn.execute(
                    "SELECT timestamp, price, volume, is_buyer_maker FROM market_ticks WHERE symbol = ? ORDER BY timestamp DESC LIMIT ?",
                    (symbol, limit),
                )
                rows = cur.fetchall()
                # Convert sqlite3.Row to tuples and reverse for chronological order
                return [ (r["timestamp"], r["price"], r["volume"], r["is_buyer_maker"]) for r in rows ][::-1]
        except Exception:
            logger.exception("Error fetching history")
            return []

    # ---------- Analyses ----------
    def insert_analysis(self, symbol: Optional[str], ts: float, analysis_type: str, payload: Any):
        """Store an analysis result. Payload will be JSON-serialized.
        Also update an in-memory cache so expensive recalculation can be avoided.

        Notes:
        - Uses a short retry loop on sqlite 'database is locked' OperationalError.
        - Cache update remains best-effort and non-blocking to callers.
        """
        payload_json = json.dumps(payload, default=str)
        attempts = 3
        delay = 0.05
        for attempt in range(attempts):
            try:
                with self._connect() as conn:
                    conn.execute(
                        "INSERT INTO analyses (symbol, ts, analysis_type, payload) VALUES (?, ?, ?, ?)",
                        (symbol, ts, analysis_type, payload_json),
                    )
                    conn.commit()
                # update in-memory cache (best-effort, non-critical)
                try:
                    key = (symbol, analysis_type)
                    now = time.time()
                    with self._cache_lock:
                        existing = self._analysis_cache.get(key)
                        # existing format: (cached_at, ts, payload)
                        if not existing or ts >= existing[1]:
                            # store cached insertion time, the DB ts, and the payload
                            self._analysis_cache[key] = (now, ts, payload)
                            # Evict oldest if cache grows beyond limit
                            try:
                                if len(self._analysis_cache) > self._analysis_cache_max:
                                    self._analysis_cache.popitem(last=False)
                            except Exception:
                                pass
                except Exception:
                    logger.debug("Failed to update analysis cache", exc_info=True)
                return
            except sqlite3.OperationalError as e:
                if "locked" in str(e).lower() and attempt + 1 < attempts:
                    time.sleep(delay * (2 ** attempt))
                    continue
                logger.exception("SQLite operational error inserting analysis")
                return
            except Exception:
                logger.exception("Error inserting analysis")
                return

    def get_analyses(self, symbol: Optional[str] = None, analysis_type: Optional[str] = None, limit: int = 1000):
        """Fetch analyses, optional filters."""
        try:
            with self._connect() as conn:
                params = []
                clauses = []
                if symbol is not None:
                    clauses.append("symbol = ?")
                    params.append(symbol)
                if analysis_type is not None:
                    clauses.append("analysis_type = ?")
                    params.append(analysis_type)
                where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, symbol, ts, analysis_type, payload, created_ts FROM analyses {where} ORDER BY ts DESC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                return [
                    {
                        "id": r["id"],
                        "symbol": r["symbol"],
                        "ts": r["ts"],
                        "analysis_type": r["analysis_type"],
                        "payload": json.loads(r["payload"]) if r["payload"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting analyses")
            return []

    def get_latest_analysis(self, symbol: Optional[str], analysis_type: str):
        """
        Get the most recent analysis for (symbol, analysis_type).
        Uses in-memory cache when fresh; falls back to DB and repopulates cache.

        Note: cache entries are stored as (cached_at, ts, payload). We check cached_at
        against _cache_ttl to determine freshness. When returning, we present the DB ts
        and payload to callers.
        """
        try:
            now = time.time()
            key = (symbol, analysis_type)
            with self._cache_lock:
                entry = self._analysis_cache.get(key)
                # entry -> (cached_at, ts, payload)
                if entry and (now - entry[0]) < self._cache_ttl:
                    return {"ts": entry[1], "payload": entry[2]}

            # Query DB for latest row. Handle NULL symbol specially.
            with self._connect() as conn:
                if symbol is None:
                    cur = conn.execute(
                        "SELECT ts, payload FROM analyses WHERE symbol IS NULL AND analysis_type = ? ORDER BY ts DESC LIMIT 1",
                        (analysis_type,),
                    )
                else:
                    cur = conn.execute(
                        "SELECT ts, payload FROM analyses WHERE symbol = ? AND analysis_type = ? ORDER BY ts DESC LIMIT 1",
                        (symbol, analysis_type),
                    )
                r = cur.fetchone()
                if not r:
                    return None
                payload = json.loads(r["payload"]) if r["payload"] else None
                ts = r["ts"]
                with self._cache_lock:
                    # store (cached_at, ts, payload)
                    self._analysis_cache[key] = (time.time(), ts, payload)
                    # Evict oldest if cache grows beyond limit
                    try:
                        if len(self._analysis_cache) > self._analysis_cache_max:
                            self._analysis_cache.popitem(last=False)
                    except Exception:
                        pass
                return {"ts": ts, "payload": payload}
        except Exception:
            logger.exception("Error getting latest analysis")
            return None

    def get_or_compute_analysis(self, symbol: Optional[str], ts: float, analysis_type: str, compute_fn, force: bool = False):
        """
        Helper to return existing latest analysis if recent enough, otherwise compute using
        the provided compute_fn (callable returning payload), store it, and return it.
        This centralizes the 'check DB/cache then compute then persist' pattern to cut down
        on repeated expensive recalculations across strategies/ML pipelines.
        """
        try:
            if not force:
                existing = self.get_latest_analysis(symbol, analysis_type)
                if existing and existing["ts"] >= ts:
                    return existing

            # compute, store, and return
            payload = compute_fn()
            self.insert_analysis(symbol, ts, analysis_type, payload)
            return {"ts": ts, "payload": payload}
        except Exception:
            logger.exception("Error in get_or_compute_analysis")
            return None

    # ---------- Signals ----------
    def insert_signal(self, symbol: Optional[str], ts: float, signal: str, params: Any = None):
        """
        Insert a signal and update the in-memory recent-signals cache.
        The cache is best-effort: failures to update are non-fatal.

        Returns:
            The inserted signal row id on success, or None on failure.
        """
        try:
            params_json = json.dumps(params, default=str) if params is not None else None
            with self._connect() as conn:
                cur = conn.execute(
                    "INSERT INTO signals (symbol, ts, signal, params) VALUES (?, ?, ?, ?)",
                    (symbol, ts, signal, params_json),
                )
                conn.commit()
                sid = cur.lastrowid
            # update cache (best-effort)
            try:
                with self._cache_lock:
                    if symbol not in self._signals_cache:
                        self._signals_cache[symbol] = {"ts": time.time(), "data": []}
                    entry = self._signals_cache[symbol]
                    # prepend for newest-first ordering and keep up to a reasonable cap
                    entry["data"].insert(0, {"symbol": symbol, "ts": ts, "signal": signal, "params": params, "id": sid})
                    entry["data"] = entry["data"][:1000]
                    entry["ts"] = time.time()
            except Exception:
                logger.debug("Failed to update signals cache", exc_info=True)
            return sid
        except Exception:
            logger.exception("Error inserting signal")
            return None

    def get_signals(self, symbol: Optional[str] = None, limit: int = 1000):
        """
        Fetch signals. If a recent cached value exists for the symbol, return that (best-effort).
        Otherwise query the DB and refresh the cache.
        """
        try:
            now = time.time()
            if symbol is not None:
                with self._cache_lock:
                    cached = self._signals_cache.get(symbol)
                    if cached and (now - cached["ts"]) < self._cache_ttl:
                        return cached["data"][:limit]

            with self._connect() as conn:
                params = []
                clauses = []
                if symbol is not None:
                    clauses.append("symbol = ?")
                    params.append(symbol)
                where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, symbol, ts, signal, params, created_ts FROM signals {where} ORDER BY ts DESC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                results = [
                    {
                        "id": r["id"],
                        "symbol": r["symbol"],
                        "ts": r["ts"],
                        "signal": r["signal"],
                        "params": json.loads(r["params"]) if r["params"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
                # refresh cache for this symbol (if specified)
                try:
                    if symbol is not None:
                        with self._cache_lock:
                            self._signals_cache[symbol] = {"ts": time.time(), "data": results}
                except Exception:
                    logger.debug("Failed to refresh signals cache")
                return results
        except Exception:
            logger.exception("Error getting signals")
            return []

    def get_signals_since(self, symbol: Optional[str], since_ts: float = 0.0, limit: int = 1000):
        """Fetch signals for a symbol with ts >= since_ts (ordered newest-first)."""
        try:
            with self._connect() as conn:
                params = []
                clauses = []
                if symbol is not None:
                    clauses.append("symbol = ?")
                    params.append(symbol)
                clauses.append("ts >= ?")
                params.append(since_ts)
                where = "WHERE " + " AND ".join(clauses)
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, symbol, ts, signal, params, created_ts FROM signals {where} ORDER BY ts DESC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                return [
                    {
                        "id": r["id"],
                        "symbol": r["symbol"],
                        "ts": r["ts"],
                        "signal": r["signal"],
                        "params": json.loads(r["params"]) if r["params"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting signals since")
            return []

    # ---------- Trades ----------
    def insert_trade(self, symbol: Optional[str], ts: float, action: str, price: float, quantity: float, user_id: int = 0, metadata: Any = None):
        """
        Insert a trade record and return the new trade id (best-effort).
        """
        try:
            meta_json = json.dumps(metadata, default=str) if metadata is not None else None
            with self._connect() as conn:
                cur = conn.execute(
                    "INSERT INTO trades (user_id, symbol, ts, action, price, quantity, metadata) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (user_id, symbol, ts, action, price, quantity, meta_json),
                )
                conn.commit()
                return cur.lastrowid
        except Exception:
            logger.exception("Error inserting trade")
            return None

    def get_trades(self, user_id: Optional[int] = None, symbol: Optional[str] = None, limit: int = 1000):
        try:
            with self._connect() as conn:
                params = []
                clauses = []
                if user_id is not None:
                    clauses.append("user_id = ?")
                    params.append(user_id)
                if symbol is not None:
                    clauses.append("symbol = ?")
                    params.append(symbol)
                where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, user_id, symbol, ts, action, price, quantity, metadata, created_ts FROM trades {where} ORDER BY ts DESC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                return [
                    {
                        "id": r["id"],
                        "symbol": r["symbol"],
                        "ts": r["ts"],
                        "action": r["action"],
                        "price": r["price"],
                        "quantity": r["quantity"],
                        "metadata": json.loads(r["metadata"]) if r["metadata"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting trades")
            return []

    def get_trades_between(self, symbol: Optional[str], start_ts: float, end_ts: float, limit: int = 1000):
        """Fetch trades for a symbol between start_ts and end_ts (inclusive), ordered oldest-first."""
        try:
            with self._connect() as conn:
                params = []
                clauses = []
                if symbol is not None:
                    clauses.append("symbol = ?")
                    params.append(symbol)
                clauses.append("ts >= ?")
                params.append(start_ts)
                clauses.append("ts <= ?")
                params.append(end_ts)
                where = "WHERE " + " AND ".join(clauses)
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, symbol, ts, action, price, quantity, metadata, created_ts FROM trades {where} ORDER BY ts ASC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                return [
                    {
                        "id": r["id"],
                        "symbol": r["symbol"],
                        "ts": r["ts"],
                        "action": r["action"],
                        "price": r["price"],
                        "quantity": r["quantity"],
                        "metadata": json.loads(r["metadata"]) if r["metadata"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting trades between")
            return []

    def insert_signal_trade(self, signal_id: int, trade_id: int):
        """
        Insert a mapping between a persisted signal and a persisted trade.
        Best-effort: failures are logged but not raised.
        """
        try:
            with self._connect() as conn:
                conn.execute(
                    "INSERT INTO signal_trade_map (signal_id, trade_id, ts) VALUES (?, ?, ?)",
                    (signal_id, trade_id, time.time()),
                )
                conn.commit()
        except Exception:
            logger.exception("Error inserting signal_trade mapping")

    # ---------- Positions (upsert) ----------
    def upsert_position(self, symbol: str, quantity: float, user_id: int = 0, avg_price: Optional[float] = None, metadata: Any = None):
        """Insert or update a persistent position for symbol."""
        try:
            meta_json = json.dumps(metadata, default=str) if metadata is not None else None
            now_ts = time.time()
            with self._connect() as conn:
                conn.execute(
                    """
                    INSERT INTO positions (user_id, symbol, quantity, avg_price, metadata, updated_ts)
                    VALUES (?, ?, ?, ?, ?, ?)
                    ON CONFLICT(user_id, symbol) DO UPDATE SET
                        quantity=excluded.quantity,
                        avg_price=COALESCE(excluded.avg_price, positions.avg_price),
                        metadata=excluded.metadata,
                        updated_ts=excluded.updated_ts
                    """,
                    (user_id, symbol, quantity, avg_price, meta_json, now_ts),
                )
                conn.commit()
        except Exception:
            logger.exception("Error upserting position")

    def get_position(self, symbol: str, user_id: int = 0):
        try:
            with self._connect() as conn:
                cur = conn.execute(
                    "SELECT user_id, symbol, quantity, avg_price, metadata, updated_ts FROM positions WHERE user_id = ? AND symbol = ?",
                    (user_id, symbol),
                )
                r = cur.fetchone()
                if not r:
                    return None
                return {
                    "user_id": r["user_id"],
                    "symbol": r["symbol"],
                    "quantity": r["quantity"],
                    "avg_price": r["avg_price"],
                    "metadata": json.loads(r["metadata"]) if r["metadata"] else None,
                    "updated_ts": r["updated_ts"],
                }
        except Exception:
            logger.exception("Error getting position")
            return None

    # ------------------------------
    # Compatibility wrappers (legacy callers expect these names)
    # ------------------------------
    def get_positions(self, user_id: Optional[int] = None) -> List[dict]:
        """
        Return all positions as a list of dicts.
        """
        try:
            with self._connect() as conn:
                params = []
                where = ""
                if user_id is not None:
                    where = "WHERE user_id = ?"
                    params.append(user_id)
                cur = conn.execute(
                    f"SELECT user_id, symbol, quantity, avg_price, metadata, updated_ts FROM positions {where}",
                    params
                )
                rows = cur.fetchall()
                return [
                    {
                        "user_id": r["user_id"],
                        "symbol": r["symbol"],
                        "quantity": r["quantity"],
                        "avg_price": r["avg_price"],
                        "metadata": json.loads(r["metadata"]) if r["metadata"] else None,
                        "updated_ts": r["updated_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting positions")
            return []

    def get_open_positions(self) -> List[dict]:
        """
        Alias for get_positions - kept for compatibility with older code.
        """
        return self.get_positions()

    # ---------- Wallets ----------
    def upsert_wallet(self, user_id: int, balances: dict, vault: dict):
        """Persist wallet state to DB."""
        try:
            now_ts = time.time()
            balances_json = json.dumps(balances)
            vault_json = json.dumps(vault)
            with self._connect() as conn:
                conn.execute(
                    """
                    INSERT INTO wallets (user_id, balances, vault, updated_ts)
                    VALUES (?, ?, ?, ?)
                    ON CONFLICT(user_id) DO UPDATE SET
                        balances=excluded.balances,
                        vault=excluded.vault,
                        updated_ts=excluded.updated_ts
                    """,
                    (user_id, balances_json, vault_json, now_ts)
                )
                conn.commit()
        except Exception:
            logger.exception("Error upserting wallet")

    def get_wallet_state(self, user_id: int):
        """Retrieve wallet state from DB."""
        try:
            with self._connect() as conn:
                cur = conn.execute("SELECT balances, vault FROM wallets WHERE user_id = ?", (user_id,))
                row = cur.fetchone()
                if row:
                    return {
                        "balances": json.loads(row["balances"]),
                        "vault": json.loads(row["vault"])
                    }
                return None
        except Exception:
            logger.exception("Error getting wallet state")
            return None

    def insert_position(self, symbol: str, ts: float, side: str, price: float, quantity: float, metadata: Any = None):
        """
        Legacy-style insert helper for callers that expect insert_position signature.
        Maps into upsert_position (preferred).
        """
        try:
            meta = metadata if metadata is not None else {"side": side}
            # Use upsert to ensure idempotency
            self.upsert_position(symbol=symbol, quantity=quantity, avg_price=price, metadata=meta)
        except Exception:
            logger.exception("Error inserting legacy position")

    # ---------- Performance metrics ----------
    def insert_metric(self, metric_name: str, value: float, ts: Optional[float] = None, tags: Any = None):
        try:
            ts = ts if ts is not None else time.time()
            tags_json = json.dumps(tags, default=str) if tags is not None else None
            with self._connect() as conn:
                conn.execute(
                    "INSERT INTO performance_metrics (ts, metric_name, value, tags) VALUES (?, ?, ?, ?)",
                    (ts, metric_name, value, tags_json),
                )
                conn.commit()
        except Exception:
            logger.exception("Error inserting metric")

    def get_metrics(self, metric_name: Optional[str] = None, limit: int = 1000):
        try:
            with self._connect() as conn:
                params = []
                clauses = []
                if metric_name is not None:
                    clauses.append("metric_name = ?")
                    params.append(metric_name)
                where = ("WHERE " + " AND ".join(clauses)) if clauses else ""
                limit = int(limit)
                cur = conn.execute(
                    f"SELECT id, ts, metric_name, value, tags, created_ts FROM performance_metrics {where} ORDER BY ts DESC LIMIT ?",
                    (*params, limit),
                )
                rows = cur.fetchall()
                return [
                    {
                        "id": r["id"],
                        "ts": r["ts"],
                        "metric_name": r["metric_name"],
                        "value": r["value"],
                        "tags": json.loads(r["tags"]) if r["tags"] else None,
                        "created_ts": r["created_ts"],
                    }
                    for r in rows
                ]
        except Exception:
            logger.exception("Error getting metrics")
            return []

    def close(self):
        """Graceful shutdown/cleanup for Database. Clears caches and marks instance for GC."""
        try:
            with self._cache_lock:
                self._analysis_cache.clear()
                self._signals_cache.clear()
        except Exception:
            logger.debug("Database.close: failed to clear caches", exc_info=True)
        # Note: connections are per-operation; nothing else to explicitly close here.

# Singleton pattern for database access
_database_instance: Optional[Database] = None
_database_lock = threading.Lock()

def get_database(db_path: Optional[str] = None) -> Database:
    """Get the global database instance (singleton)."""
    global _database_instance
    if _database_instance is None:
        with _database_lock:
            if _database_instance is None:
                if db_path is None:
                    from config import get_settings
                    db_path = get_settings().DB_PATH
                _database_instance = Database(db_path)
                logger.info(f"Database singleton initialized at {db_path}")
    return _database_instance
